title: Rapture
description: Awesome videos
url: 

tags: 
  - promos
  - regie
  - camera

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  - scope:
      path: "_projects" 
    values:
      layout: "project"
      permalink: /full-portfolio/:title/


collections: 
  projects:
    output: true
